name: widgets_pack
description: Widgets collection for flutter applications
version: 0.2.15

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  chewie: ^1.8.3
  equatable: ^2.0.5
#  extensions_pack: { path: ../extensions-pack }
  extensions_pack: ^2.3.0+2
  flutter: { sdk: flutter }
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  rxdart: ^0.27.7
  skeletonizer: ^1.4.2
  sticky_headers: ^0.3.0+2
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  my_linter: ^0.1.0+3

flutter:
