name: widgets_pack
description: Widgets collection for flutter applications
version: 0.1.6

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  equatable: ^2.0.5
  extensions_pack: ^2.2.3
  flutter: { sdk: flutter }
  flutter_spinkit: ^5.2.1
  intl: ^0.18.1
  pod_player: ^0.2.1
  rxdart: ^0.27.7
  sticky_headers: ^0.3.0+2
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  my_linter: ^0.0.6

flutter:
